services:
  linkwarden:
    image: ghcr.io/podmania/linkwarden:latest
    userns_mode: "keep-id"
    container_name: linkwarden
    ports:
      
      - 3000:3000
      
    volumes:
      
      - ./data:/data
      
      - /etc/localtime:/etc/localtime:ro
    restart: always
